[build-system]
requires      = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.version]
source           = "vcs"
fallback-version = "0.1.0"

[tool.hatch.build.hooks.vcs]
version-file = "foilselector/_version.py"

[project]
name = "foilselector"
authors = [{ name = "OceanNuclear", email = "annoyingamygdala@gmail.com" }]
description = """Tools and scripts used to read nuclear data and thus select foils used in irradiation"""
dynamic = ['version']
readme = "README.rst"
license = "MIT"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python",
  "Development Status :: 3 - Alpha",
  "Natural Language :: English",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Scientific/Engineering :: Physics",
]

dependencies = [
  "numpy >=1.20.3",
  "tqdm >=4.61.1",
  "matplotlib >=3.4.2",
  "pandas >=1.2.4",
  "seaborn >=0.11.1",
  "scipy >=1.6.3",
  "openmc",
  "click",
]

[project.optional-dependencies]
dev = ["ruff", "pytest", "precommit"]
visual = ["networkx >=2.6.1"]

[project.urls]
Source        = "https://github.com/OceanNuclear/actifoilselector"
Documentation = "https://github.com/OceanNuclear/actifoilselector#readme"
Issues        = "https://github.com/OceanNuclear/actifoilselector/issues"

[project.scripts]
foilselector = "foilselector.cli:cli"

[tool.ruff]
target-version = "py310"
line-length = 89
output-format = "concise"
exclude = [
  ".git",
  "__pycache__",
  ".env",
  ".idea",
  ".pytest_cache",
  "htmlcov",
]

[tool.ruff.format]
preview = true

[tool.ruff.lint]
preview = true
select = ["ALL"]
ignore = [
  "ANN",    # type annotations
  "CPY",    # we don't need a copyright info.
  "EM",     # string in error messages
  "D205",   # description not always necessary if summary is provided.
  "DOC502", # Omit non-explicit exceptions from docstrings
  "E203",   # black/ruff format conflicts
  "FIX002", # Line contains todo
  "ISC001", # ruff format conflict
  "PLW1514",# Specify file open encoding
  "EXE",    # shebang not needed at the beginning of file.
  "ERA",    # remove commented out code
  "N80",    # Allow uppercase variables because physics variables.
  "N816",
  # The following are no longer ignored:
  # "COM812",  # enforce trailing comma, disagrees with black/ruff format
  # "TD",  # standardise TODOs
  # "PTH123",  # use Path.open
  "TRY003",  # put error messages in error class
  # "SLF001",  # private method use
  "T201",   # Allow print statements for now. May be changed to a log file later.
]

[tool.ruff.lint.isort]
known-first-party = ["foilselector"]
case-sensitive = true

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.pycodestyle]
max-doc-length = 89

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.per-file-ignores]
# Tests can use magic values, assertions, and relative imports
"tests/**/*" = ["PLR2004", "S101", "TID252"]
"__init__.py" = ["F401", "F403"]
"foilselector/foldermanagement.py" = ["D103"]
"foilselector/script/*.py" = ["W505", "E501", "PLR0913", "PLR0917"]
"foilselector/cli.py" = ["PLR0913", "PLR0917"]
"*/__init__.py" = ["D104"]
