"""
Module to turn build the decay graph (a directed-acyclic-graph (DAG)),
turn it into a tree,
and then linearize the tree
    so that each way of reaching each node in the tree is accounted for using a subchain.
"""

from __future__ import annotations
import pprint
from collections import namedtuple

import numpy as np
from uncertainties.core import Variable
from foilselector.openmcextension.library_reader import flatten_photon_spectrum

class IsotopeDecay(
    namedtuple(
        "IsotopeDecayTuple",
        ["names", "branching_ratios", "decay_constants", "discrete_photon_spectrum", "background_photon_spectrum"],
    )
):
    """
    a decay chain's characteristics as detected by a gamma-ray detector.
    Attributes
    ----------
    names: list[str]
        All isotopes in that decay chain as a list.
    branching_ratio: list [uncertainties.core.Variable]
        decay branching ratios as a list of floats
    decay_constants: list [uncertainties.core.Variable]
        decay_constants as a list,
    discrete_photon_spectrum: list[DiscreteRadiation]
        Energies and intensity of photons released during the decay of a single daughter
        nuclide (i.e. decay of a single nuclide at the end of the chain.)
    background_photon_spectrum: list[ContinuousRadiationDistribution]
        Continuous distribution of photon emission probability v.s. photon energies.
    """
    def __add__(self, daughters_decay: IsotopeDecay):
        """
        __add__ is a non-commutative operation, where the daughter's info is appended
        onto the parent chain's info, but the spectrum refers to only the daughter's
        characteristic gamma-ray spectrum released during the daughter's decay.
        """
        assert daughters_decay.names[0] not in self.names, ("Expected the isotopes decay"
                " graph to form a DAG (i.e. acyclic in nature)!")
        return IsotopeDecay(
            self.names + daughters_decay.names,
            self.branching_ratios + daughters_decay.branching_ratios,
            self.decay_constants + daughters_decay.decay_constants,
            daughters_decay.discrete_photon_spectrum,
            daughters_decay.background_photon_spectrum,
        )

class DecayInfo(dict):
    """
    e.g. since Pt190_e41 doesn't exist,
    applying getitem('Pt190_e41') should fall back to the decay info of
    Pt190 (unexcited),
    i.e. we assume that the user would observe no meaningful difference between the decay of Pt190_e41 and Pt190
    since the former will directly internal transition to the latter very quickly,
    even before the user can take away the foil.
    """

    def __init__(self):
        raise NotImplementedError(
            "To be implemented at the revamp stage - when I invert the foilselector to do material selection as the first stage."
        )


def build_decay_chain_tree(
        decay_dict: dict,
        decay_parent: str,
        decay_constant_threshold=1e-23
    ) -> dict:
    """
    Build the entire decay chain (recursively) *AS A TREE* for a given starting isotope to decay from.

    This turns the decay chain (a directed-acyclic graph) into a tree.
    In order to do so sometimes we may end up with the same isotope on several different branches,
    but that's a mathematically expected behaviour,
        because if you add up the branching ratio leading down to each of these isotopes you'll get back to unity.
    We must sum across all of these instances of the identical isotopes to accurately represent
        the total number of isotopes at any point in time/ total number of decay experienced across any two points in time.

    Parameters
    ----------
    decay_dict: dict
        Each entry in decay_dict has the name of the decaying isotope as the key,
        and a dictionary of its decay-related parameters (decay_constant,
        branching_ratio, spectra) as generated by `openmc.data.Decay.from_endf(...)` and
        then transformed by `foilselector.openmcextension.extended_io._extract_decay()`.
    decay_parent: str
        names of the potentially unstable nuclide
    decay_constant_threshold: float
        Isotopes with decay rate (s^-1) below this threshold is considered stable.

    Returns
    -------
    tree: dict
        A dictionary with the following keys:

    Items of the 'tree' dict
    ------------------------
    "name": str
        name of the isotope involved in this decay chain.
    "decay_constant": uncertainties.core.Variable
        Decay constant for this particular isotope, unit: s^-1.
    "discrete_photon_spectrum":
        Energies and intensity of photons released during the decay of a single nuclide
        of this isotope.
    "background_photon_spectrum":
        background spectra of photons that cannot be measured cleanly, but forms a
        continuous distribution.
    "daughter_and_branching_ratio": list[tuple]
        A list of 2-tuples, each tuple containing:
        (daughter_tree:dict, branching_ratio: uncertainties.core.Variable)
    """
    if decay_parent not in decay_dict.keys():
        if "_" in decay_parent:
            # Is an excited isotope. So we assume it instantaneously decays, and
            # try again by replacing it with the ground state isomer.
            tree = build_decay_chain_tree(
                decay_dict, decay_parent.split("_")[0], decay_constant_threshold
            )
        else:
            # Termination criteria 1: This is a stable isotope with no decay record.
            tree = {
                "name": decay_parent,
                "decay_constant": Variable(0.0, 0.0),
                "discrete_photon_spectrum": [],
                "background_photon_spectrum": [],
                "daughter_and_branching_ratio": [], 
            }
    else: # decay_dict contains the specified decay_parent
        parent = decay_dict[decay_parent]
        discrete, background = flatten_photon_spectrum(parent["spectra"], decay_parent)
        tree = {
            "name": decay_parent,
            "decay_constant": parent["decay_constant"],
            "discrete_photon_spectrum": discrete,
            "background_photon_spectrum": background,
            "daughter_and_branching_ratio": [],
        }  # photon spectrum per decay of this isotope
        if decay_dict[decay_parent]["decay_constant"] <= decay_constant_threshold:
            # Termination criteria 2: this is a stable isotope with decay record.
            return tree
        else:
            # Recursion criteria: non-empty daughter list
            for daughter_name, branching_ratio in decay_dict[decay_parent]["branching_ratio"].items():
                if daughter_name != decay_parent: # prevent self-referencing
                    tree["daughter_and_branching_ratio"].append((
                        build_decay_chain_tree(
                            decay_dict,
                            daughter_name,
                            decay_constant_threshold
                        ),
                        branching_ratio
                    ))
    return tree


def linearize_decay_chain(decay_tree) -> list[IsotopeDecay]:
    """
    Return a comprehensive list of path-to-nodes. Each path starts from the origin, and
    ends at the node of interest. For each node in the original graph, if there are n
    distinct pathways to get to it, then it will be recorded as the end node n different
    times. The initial population is set as unity for ease of computing.
    """
    self_decay = IsotopeDecay(
        [decay_tree["name"]],
        [Variable(1.0, 0.0)], 
        # dummy branching ratio. This gets overwritten when it's acting as the daughter
        # chain in the recursion condition.
        [decay_tree["decay_constant"]],
        decay_tree["discrete_photon_spectrum"],
        decay_tree["background_photon_spectrum"],
    )
    output_chains = [self_decay,] # output of linearize(self)
    for daughter, branching_ratio in decay_tree["daughter_and_branching_ratio"]:
        for subbranch in linearize_decay_chain(daughter): # recursion condition:
            # stick the output of linearize(daughter) onto the end of linearize(self).
            # type(subbranch)==IsotopeDecay
            subbranch.branching_ratios[0] = branching_ratio
            output_chains.append(self_decay + subbranch) # parent's decay + daughter's decay.
    return output_chains


def check_differences(decay_constants):
    difference_matrix = np.diff(
        np.meshgrid(decay_constants, decay_constants)[::-1], axis=0
    )[0]
    return abs(difference_matrix)[np.triu_indices(len(decay_constants), 1)]


def trim_tree(tree):
    """
    Given a tree built from build_decay_chain_tree,
    such that when pretty-printed by pprint,
    it is easy to read and retains only the key information for each daughter nuclide (name, branching ratio)
    """
    results = {"decaying isotope": tree["name"]}
    decay_const = tree["decay_constant"]
    if decay_const > 1e-23:
        results.update({"t1/2": ln2 / decay_const})
    else:
        results.update({"t1/2": np.inf})
    if tree["daughter_and_branching_ratio"]:
        results.update({
            " L=>": [
                (ratio, trim_tree(daughter))
                for daughter, ratio in tree["daughter_and_branching_ratio"]
            ]
        })
    return results


def pprint_tree(decay_tree):
    """
    Print the decay tree in a pretty/readable format
    """
    return pprint.pprint(trim_tree(decay_tree), sort_dicts=False)
